
Mrsool/LetsNot:
  Description: 'Do not use `let` in rspec'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/SystemTests:
  Description: 'Prefer :system to :feature'
  Enabled: true
  VersionAdded: '0.1.0'
