
Mrsool/DbMigrationTimestamp:
  Description: 'Do not forget to commit structure.sql after adding a migration'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/DoNotUseDeleteMatched:
  Description: 'Do not use delete_matched, use RedisHashStore#delete_hash instead'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/LetsNot:
  Description: 'Do not use `let` in rspec'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/OrderBuyerId:
  Description: 'Do not use order.iBuyerId'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/SpecGlobalMethod:
  Description: 'Do not add global methods to spec files'
  Enabled: true
  VersionAdded: '0.1.0'

Mrsool/SystemTests:
  Description: 'Prefer :system to :feature'
  Enabled: true
  VersionAdded: '0.1.0'
